import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "van-garf",
  description: "Generated by create-vinext-app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
